### ISSUE TITLE
Du redigere denne side

### ISSUE THREAD

**Issue by Simon9877** [F5-ApS/F5-ApS-website#38]
# Details 
Du redigerede denne side

| Submitted by | URL | Screenshot | Device(s) | Browser(s) |
| --- | --- | --- | --- | --- |
| jane.s@f5.dk | https://testdev.f5.dk/admin/desk/pages;masterclass |  | Computer | Google Chrome/Microsoft Edge |

**Comment by rkarmark** [comment]
Needs more info
